---
kind: pipeline
type: docker
name: linux

trigger:
  event: 
    - tag

platform:
  os: linux
  arch: amd64

workspace:
  path: /home/circleci/project/

steps:
- name: prepare
  image: cimg/android:2022.03.1-ndk
  environment:
    TEST: 1
  commands:
    - sudo apt update && sudo apt -y install swig clang-12
    - ./build-linux.sh

- name: libs
  image: plugins/github-release
  settings:
    api_key:
      from_secret: release_token
    files: libo3lib-*
    title: test

- name: wrapper.h
  image: plugins/github-release
  settings:
    api_key:
      from_secret: release_token
    files: o3lib_wrap.h
    title: ${DRONE_TAG}

- name: wrapper.go
  image: plugins/github-release
  settings:
    api_key:
      from_secret: release_token
    files: o3lib.go
    title: ${DRONE_TAG}

    
---
kind: secret
name: release_token
get:
  path: kv/data/ops/github
  name: release_token